### ISSUE TITLE
Emulator doesn't read most keyboard symbols

### ISSUE THREAD

**Issue by Candid-Moe** [Zeal8bit/Zeal-WebEmulator#14]
Using the emulator, it doesn't register many non-letter keys like "+", "[", "]", "{", "}". I pressed every key, but none give me a "+".

The real thing works OK, however.

**Comment by Zeal8bit** [comment]
Hello @Candid-Moe ,

I just moved the issue to the Emulator project since this is related to the emulator and not the OS.
This bug is due to Firefox and Chrome-based browsers having different codes for key presses. I was able to reproduce the issue with the ':' not showing on Firefox though, even with a US keyboard.

Is that a Spanish keyboard? If yes, I can try this layout on my end.
